### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by thomasdierickx** [thomasdierickx/MIP#13]

**Comment by SimonVanherweghe** [comment]
https://github.com/thomasdierickx/MIP/blob/main/README.md

Concept is op zich ok, maar ik mis uitleg over de technische zaken.
Welke nieuwe/ongeziene technologie ga je implementeren? Welke services ga je gebruiken? Welke stack? Nextjs +....? Check de opdrachtfiche voor meer duiding.
